# Generated by Django 5.1.7 on 2025-03-19 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('specialty', models.CharField(max_length=100)),
                ('secondary_specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(max_length=100)),
                ('license_state', models.CharField(max_length=100)),
                ('years_experience', models.CharField(choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6-10', '6-10 years'), ('11-15', '11-15 years'), ('16-20', '16-20 years'), ('20+', '20+ years')], max_length=10)),
                ('languages', models.CharField(max_length=255)),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_address', models.CharField(max_length=255)),
                ('clinic_city', models.CharField(max_length=100)),
                ('clinic_state', models.CharField(max_length=100)),
                ('clinic_zip', models.CharField(max_length=20)),
                ('clinic_phone', models.CharField(max_length=20)),
                ('clinic_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('medical_school', models.CharField(max_length=255)),
                ('graduation_year', models.IntegerField()),
                ('degree', models.CharField(max_length=255)),
                ('residency', models.CharField(blank=True, max_length=255, null=True)),
                ('fellowship', models.CharField(blank=True, max_length=255, null=True)),
                ('board_certification', models.CharField(blank=True, max_length=255, null=True)),
                ('other_qualifications', models.TextField(blank=True, null=True)),
                ('about_me', models.TextField()),
                ('services', models.TextField()),
                ('insurances', models.TextField(blank=True, null=True)),
                ('hospital_affiliations', models.TextField(blank=True, null=True)),
                ('subscription_plan', models.CharField(choices=[('basic', 'Basic Plan - $29/month'), ('professional', 'Professional Plan - $49/month'), ('premium', 'Premium Plan - $99/month')], default='professional', max_length=20)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('data_consent', models.BooleanField(default=False)),
                ('verification_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('profile_photo', 'Profile Photo'), ('medical_license', 'Medical License'), ('medical_degree', 'Medical Degree Certificate'), ('additional_certificate', 'Additional Certificate')], max_length=30)),
                ('file', models.FileField(upload_to='doctor_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='doctors.doctor')),
            ],
        ),
    ]
