# Generated by Django 5.1.7 on 2025-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_appointment_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(blank=True, help_text='Unique 6-character hexadecimal ID', max_length=6, null=True, unique=True),
        ),
    ]