# Generated by Django 5.2 on 2025-04-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_add_zoom_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='doctors_sup_ticket__7d179f_idx',
            old_name='doctors_sup_ticket__68dcbe_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='doctors_sup_status_fa85b0_idx',
            old_name='doctors_sup_status_af2c55_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='doctors_sup_doctor__64bf47_idx',
            old_name='doctors_sup_doctor__f0bcc1_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='doctors_sup_patient_bbe27b_idx',
            old_name='doctors_sup_patient_30ec85_idx',
        ),
    ]
