# Generated by Django 5.2 on 2025-04-22 12:07
# This is a maintenance migration to ensure database sync after manual SQL fixes
# It serves as documentation that field additions from migration 0009 
# have been successfully applied to the database

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_rename_doctors_sup_ticket__68dcbe_idx_doctors_sup_ticket__7d179f_idx_and_more'),
    ]

    operations = [
        # No operations - this migration documents that Zoom fields were added directly to the database
        # and the migration system is now in sync with the actual database schema
    ]